---
title: "Mercado Inmobiliario Mar del Plata"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r echo = FALSE, message = FALSE, warning = FALSE}
library(knitr)
source('pre-proc.R')
library(tidyverse)
mardel_oct = read_csv('octubre_mardel.csv')
mardel_nov = read_csv('mardel_limpio.csv')
mardel_dec = read_csv('mardel_dec_limpio.csv')

mardel = rbind(mardel_oct, mardel_nov %>% dplyr::select(colnames(mardel_oct)),mardel_dec %>% select(colnames(mardel_oct))) %>% distinct(id, .keep_all = T)


mardel_summary = function(mardel){
  mardel %>% group_by(Tipo) %>% 
    summarise(
      Cantidad = n(),
      Precio_M2 = mean(p.x.m2, na.rm = T) %>% round(),
      Tamaño = mean(Metros, na.rm = T)%>% round(),
      Precio = mean(Prices, na.rm = T)%>% round()
      
      ) %>% arrange(-Cantidad) %>% head(10)
  
  
}


mardeltalbe1 = mardel_summary(mardel)
```


```{r echo = FALSE, message = FALSE, warning = FALSE}
library(scales)

library(ggpubr)

library(lubridate)
summ_oct = mardel_summary(mardel_oct)
summ_nov = mardel_summary(mardel_nov)
summ_dec = mardel_summary(mardel_dec)
summ_dec['Mes'] = ymd("2019-12-01")
summ_nov['Mes'] = ymd("2019-11-01")
summ_oct['Mes'] = ymd("2019-10-01")
summ_all = rbind(summ_oct,summ_nov,summ_dec)



p1<-summ_all %>% filter(Cantidad>500) %>% ggplot(aes(x = Mes, y = Tamaño))+
  geom_line(aes(color = Tipo, group = Tipo),size = 1)+labs(title="Tamaño del Inmueble")+
  geom_point(aes(color = Tipo))+theme_bw()+ theme(legend.position = "none")+
  scale_x_date(date_breaks = "1 month",labels = date_format("%b"))+ theme(plot.title = element_text(size=10))



p2<-summ_all %>% filter(Cantidad>500) %>% ggplot(aes(x = Mes, y = Precio))+
  geom_line(aes(color = Tipo, group = Tipo),size = 1)+labs(title="Precio del Inmueble")+
  geom_point(aes(color = Tipo))+theme_bw()+ theme(legend.position = "bottom")+
  scale_x_date(date_breaks = "1 month",labels = date_format("%b"))+ theme(plot.title = element_text(size=10))




p3<-summ_all %>% filter(Cantidad>500) %>% ggplot(aes(x = Mes, y = Precio_M2))+
  geom_line(aes(color = Tipo, group = Tipo),size = 1)+labs(title="Precio por M² del Inmueble")+
  geom_point(aes(color = Tipo))+theme_bw()+scale_x_date(date_breaks = "1 month",labels = date_format("%b"))+ theme(legend.position = "none")+ theme(plot.title = element_text(size=10))




```
```{r echo = FALSE, message = FALSE, warning = FALSE}
bajaron_table = read_csv('bajaron_table.csv')
```


```{r echo = FALSE, message = FALSE, warning = FALSE}
source('informe_data.R')

```


```{r echo = FALSE, message = FALSE, warning = FALSE}
library(leaflet)
library("KernSmooth")
library("raster")
library(data.table)
#trimestr =rbind(mardel_oct, mardel_nov %>% select(colnames(mardel_oct)),mardel_dec %>% #select(colnames(mardel_oct))) %>% distinct(id, .keep_all = T)

plot_mardel = function(mardel){
  library(leaflet)
  library("KernSmooth")
  library("raster")
  library(data.table)
  mardelat = mean(mardel$Latitud, na.rm = T)
  mardelong = mean(mardel$Longitud, na.rm = T)
  colnames(mardel)[colnames(mardel)=='Latitud']  = 'latitude'
  colnames(mardel)[colnames(mardel)=='Longitud']  = 'longitude'
  
  
  dat <- data.table(mardel)
  setnames(dat, tolower(colnames(dat)))
  setnames(dat, gsub(" ", "_", colnames(dat)))
  dat <- dat[!is.na(longitude)]
  ## Create kernel density output
  kde <- bkde2D(dat[, list(longitude, latitude)],
                bandwidth = c(.0045, .0068),
                gridsize = c(2500, 2500))
  KernelDensityRaster <-
    raster(list(
      x = kde$x1 ,
      y = kde$x2 ,
      z = kde$fhat
    ))
  KernelDensityRaster@data@values[which(KernelDensityRaster@data@values < 1)] <-
    NA
  kernel_density_values <- KernelDensityRaster@data@values
  KernelDensityRaster@data@values=log(KernelDensityRaster@data@values,10)
  
  #create pal function for coloring the raster
  palRaster <-colorNumeric("Spectral",domain = KernelDensityRaster@data@values,na.color = "transparent")
  
  ## Redraw the map 
  #palRaster <- colorBin("Spectral",domain = KernelDensityRaster@data@values, na.color = "transparent")
  palRaster1 <- colorBin("Spectral",domain = 10^KernelDensityRaster@data@values, na.color = "transparent")
  
  leaflet() %>% setView(lng = mean(mardel$longitude,na.rm = T), lat = mean(mardel$latitude,na.rm = T), zoom = 10)%>% addTiles() %>%
    addLegend(pal = palRaster1,
              values = 10^KernelDensityRaster@data@values,
              title = "Densidad de Oferta Inmobiliaria") %>% 
    addRasterImage(KernelDensityRaster,
                   colors = palRaster,
                   opacity = .65)
    
}

## Redraw the map
if(knitr::is_html_output()) {
  plot_mardel(mardel)
} else {
  library("png")
  pp <- readPNG("mapamardel.png")
  plot.new()
  rasterImage(pp, 0, 0, 1, 1)
}

```


```{r echo = FALSE, message = FALSE, warning = FALSE}
zona_precio_heatmap 
```

