ANALYSIS OF SUPPLY AND EVOLUTION OF THE REAL STATE MARKET
---------------------------------------------------------

The real state market is composed of a series of goods and sevices that
are heterogeneous in their characteristics and in their localization

The features of each of the housing units in supply are, together, the
features of the market in general in a given timeframe

Usually, what is obvserved is the supply stock and it is assumed that
the price is in equilibrium, in this sense, the supply is fixing a price
which will allow them to sell or rent at a price in the least amount of
time. Nevertheless, the flux of actual sales is not observable in this
sample, but it might be yet possible to determine by analysing the
changes in supply over time

The scrapping methods takes the data monthly in order to get the
necessary data to perform such analysis.

In this presentation, we'll give a view of the supply. Leaving the
demand analysis for future oportunity

Study of supply
---------------

The total amount of registers we have for the third trimester of 2019 in
our scrapping, once deleted repeated adds, is roughly 25675; of which
15562 are apartments and 5489 to houses.

The next table is a summary of total and average squared meters, and
their values in US Dollars for Mar del Plata

**references** Departamento = Apartment Casa = House PH = Horizontal
Property, a building with housing units much bigger that apartments but
has less than 3 floors Terreno = Land Local Comercial = Comerce shop
Local Comercial = Comerce office Garage = Garage Fondo de Comercio =
On-going business in sale Bodega-Galpon = shed (as big as a block
usually) Edificio = Building

<table>
<caption>Features of Sales dataset</caption>
<thead>
<tr class="header">
<th align="left">Tipo</th>
<th align="right">Cantidad</th>
<th align="right">Precio_M2</th>
<th align="right">Tamaño</th>
<th align="right">Precio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Departamento</td>
<td align="right">15562</td>
<td align="right">2066</td>
<td align="right">70</td>
<td align="right">138747</td>
</tr>
<tr class="even">
<td align="left">Casa</td>
<td align="right">5489</td>
<td align="right">811</td>
<td align="right">434</td>
<td align="right">245960</td>
</tr>
<tr class="odd">
<td align="left">PH</td>
<td align="right">1645</td>
<td align="right">1207</td>
<td align="right">101</td>
<td align="right">99352</td>
</tr>
<tr class="even">
<td align="left">Terrenos</td>
<td align="right">1451</td>
<td align="right">743</td>
<td align="right">700</td>
<td align="right">316334</td>
</tr>
<tr class="odd">
<td align="left">Local comercial</td>
<td align="right">659</td>
<td align="right">1751</td>
<td align="right">208</td>
<td align="right">197579</td>
</tr>
<tr class="even">
<td align="left">Oficina comercial</td>
<td align="right">287</td>
<td align="right">1569</td>
<td align="right">98</td>
<td align="right">125887</td>
</tr>
<tr class="odd">
<td align="left">Garage</td>
<td align="right">245</td>
<td align="right">912</td>
<td align="right">1932</td>
<td align="right">803429</td>
</tr>
<tr class="even">
<td align="left">Fondo de Comercio</td>
<td align="right">132</td>
<td align="right">1221</td>
<td align="right">968</td>
<td align="right">1340016</td>
</tr>
<tr class="odd">
<td align="left">Bodega-Galpón</td>
<td align="right">99</td>
<td align="right">611</td>
<td align="right">875</td>
<td align="right">336943</td>
</tr>
<tr class="even">
<td align="left">Edificio</td>
<td align="right">51</td>
<td align="right">1737</td>
<td align="right">759</td>
<td align="right">887350</td>
</tr>
</tbody>
</table>

From this table it came out that 82.16% of the supply is composed by
Departamento (60.74%) y Casa (21.42%) and that the apartments have the
highest prices by squared meter and the least change in supply

Likewise the data reveal the variation in quantities, prices and sizes
of each type of housing unit


<img src="/img/unnamed-chunk-3-1.png" />


In this case we can see, for example, that, for apartments, the rise in
size (total squared meters) causes that, even though the total price
risses, the price by squared meters falls. The oposite occurs for the
PH's

The dataset also provides housing units that have activaly reduce it's
prices in the last three months

<table>
<caption>Bajaron de Precio</caption>
<thead>
<tr class="header">
<th align="left">Tipo</th>
<th align="right">Cantidad</th>
<th align="left">Bajó</th>
<th align="right">Precio_M2</th>
<th align="left">var Precio m2</th>
<th align="right">Tamaño</th>
<th align="left">var Tamaño</th>
<th align="right">Precio</th>
<th align="left">var Precio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Departamento</td>
<td align="right">207</td>
<td align="left">8.63%</td>
<td align="right">1891</td>
<td align="left">-13.51%</td>
<td align="right">54</td>
<td align="left">-33.65%</td>
<td align="right">100875</td>
<td align="left">-35.72%</td>
</tr>
<tr class="even">
<td align="left">PH</td>
<td align="right">10</td>
<td align="left">9.80%</td>
<td align="right">1173</td>
<td align="left">12.05%</td>
<td align="right">81</td>
<td align="left">-50.80%</td>
<td align="right">91780</td>
<td align="left">-27.27%</td>
</tr>
</tbody>
</table>

In the table we can see that the average price of apartments drop 8.63%,
meanwhile the prices of the PHs dropped even more, an average of 9.8%.

The housing units that lowered the price also present a series of
features we can exam.

The prices for squared meter that lowered the price are 13.5% cheaper
than the overall average, meaning that those which lower the price were
already cheaper than the overall sample. The same for sizes

The PH's have a peculiar feature. Even though, those which lowered the
price are smaller than the general sample, the price by squared meter is
higher. This is because the difference between the average size si
higher than the difference between the price of the housing unit

Real State brokers
------------------

The dataset provides as well, the real state broker since november 2019.
This allows us to evaluate better who is offering.

To begin with, we can see that the majority of the brokers have a few
publications, 77% have less than 22 in this trimester. But there is also
brokers with a lot of publications; 1% of the brokers have between 276
and 419 publications

<img src="/img/unnamed-chunk-6-1.png" />


This data can also be used to track the market-share of each broker, and
analyse the evolution

Zones of Supply Density
-----------------------

The data is geolocated in 97%, which permits us to map it and visualize
the density of the real state supply. As expected, the major density are
near the center of town, near the bus terminal and near the cost; given
that Mar del Plata is a major tourist center

![](informeMKD_EN_files/figure-markdown_strict/unnamed-chunk-7-1.png)

<img src="/img/unnamed-chunk-7-1.png" />


A further anlysis of each zone can be made, so we can describe them

<img src="/img/unnamed-chunk-8-1.png" />

![](informeMKD_EN_files/figure-markdown_strict/unnamed-chunk-8-1.png)

Overall, how is the supply distributed in each zone?

<img src="/img/unnamed-chunk-9-1.png" />


![](informeMKD_EN_files/figure-markdown_strict/unnamed-chunk-9-1.png)

Esto nos dice que si bien la zona 6 ocupa el 10% de los m² ofrecidos,
constituye el 26% de las publicaciones. Y, conjuntamente con la zona 5,
son el 25% de los m² ofrecidos, pero superan el 52% del total de
publicaciones. This tell us that, even though zone 6 occupies 10% the m²
offered, is 26% of the publications. And, toghether with zone 5, they
are more than 52% of the publications

The variables than will be described for each zone are:

-   Type of housing unit
-   Size in squared meters
-   Price by squared meter
-   Total price

### Type

Below, we can see that the zone of least density (zone 0), the market is
composed mainly with land and houses. And as we advance to the zone of
major density (zone 6) the composition of the supply varies. In the
first place, the land are no longer offered, the apartments takes over
as the main type and in the center of town also appears comercial shops
and garages

![](informeMKD_EN_files/figure-markdown_strict/unnamed-chunk-10-1.png)

This is exactly what one would expect, if the housing unit is smaller,
more units fit in a given space

### Sizes

The sizes of each unit play a fundamental role in the geographical
concentration of the supply

![](informeMKD_EN_files/figure-markdown_strict/unnamed-chunk-11-1.png)

As we saw in the "Type" section, we can quantify how the types which are
traditionaly the largest (houses, land) affect the concentration

### Prices

The prices in each area are more homogeneous than the sizes or any other
variable previously analyse. There is still a tendency that more supply
means less prices. For example, the least average price is in zone 6

![](informeMKD_EN_files/figure-markdown_strict/unnamed-chunk-12-1.png)

This information, doesn't reflect how the prices varies in each zone.
Prices in zone 6 may be the least, in average, but this prices hide a
major variabilty. Prices in zone 6 have 50% variation than in zone 0.
Meaning that, even though the prices are lower, in average, there are a
lot with higher prices, and with lower prices. And in zones where houses
are the main unit, the prices are more steady

### Price by squared meter

This a sort of conclution of the two previous parts. We saw that the
units gets larger in less concentrated areas, and the total prices
doesn't change that much. This means that the prices by squared meter
will be higher there where there is a major supply concentration

![](informeMKD_EN_files/figure-markdown_strict/unnamed-chunk-13-1.png)

### As price zones...

The same methology can be used to extract different zones, Prices,
number of rooms, etc which can be made ad hoc

![](informeMKD_EN_files/figure-markdown_strict/unnamed-chunk-14-1.png)

Some of the alternative maps can be seen in: [mapa
interactivo](https://lucariel.shinyapps.io/mapa_inmobiliario/)
